### ISSUE TITLE
Didn't catch on v135.1 and v135.2

### ISSUE THREAD

**Issue by TobTobXX** [flathub/com.github.Anuken.Mindustry#40]
- [v135.1](https://github.com/Anuken/Mindustry/commit/4462bcca438b39811861aae52fdf0f4744129809) came out 5 days ago
- [v135.2](https://github.com/Anuken/Mindustry/commit/41b22ba6a64b748b9dbcb9d0b2fdccc054f0ab17) came out 3 days ago

somehow the data checker didn't catch on to these tags?

**Comment by muelli** [comment]
maybe because of the dot.
here's the regex: https://github.com/flathub/com.github.Anuken.Mindustry/blob/0bb34e23699f14bfb12c622aec2a5fd2e5e76b5b/com.github.Anuken.Mindustry.yml#L59

**Comment by TobTobXX** [comment]
Hmm... it seems to work?

```
~/p/f/com.github.Anuken.Mindustry > flatpak run org.flathub.flatpak-external-data-checker --check-outdated com.github.Anuken.Mindustry.yml                                                      0.492s  (beta) 14:04
INFO    src.manifest: Loading sources from gradle-sources.json
INFO    src.manifest: Checking 238 external data items
INFO    src.manifest: Started check [1/238] git Mindustry (from com.github.Anuken.Mindustry.yml)
INFO    src.manifest: Skipped check [2/238] file gradle-7.3-bin.zip (from com.github.Anuken.Mindustry.yml)
INFO    src.manifest: Skipped check [3/238] file asm-3.3.1.pom (from gradle-sources.json)
[...]
INFO    src.manifest: Skipped check [238/238] file annotations-13.0.jar (from gradle-sources.json)
INFO    src.lib.externaldata: Source Mindustry: got new version 135.2
INFO    src.manifest: Finished check [238/238] git Mindustry (from com.github.Anuken.Mindustry.yml)
CHANGE SOON: Mindustry
 Has a new version:
  URL:       https://github.com/Anuken/Mindustry
  Commit:    41b22ba6a64b748b9dbcb9d0b2fdccc054f0ab17
  Tag:       v135.2
  Branch:    None
  Version:   135.2
  Timestamp: None

INFO    src.main: Check finished with 0 error(s)
```

No idea why the PR doesn't land.

**Comment by TheEvilSkeleton** [comment]
Turns out, flatpak-external-data-checker doesn't automatically check for updates if the branch in question isn't the default branch. I implemented https://github.com/flathub/com.github.Anuken.Mindustry/commit/e06eb475c7b3fbd1641342487d28dccd613e007c. Hopefully everything works without a problem.
